BTHAB-188: Allow decimal quantity when editting line item
compucorp/lineitemedit pull request #4
Opened 2023-06-12 08:40 UTC by olayiwola-compucorp

## Overview
This PR allows users to input decimal quantities when editing a line item

## Before
Users can input decimal quantities when creating new line items, but cannot input decimal quantities when editing the line items.

![polik](https://github.com/compucorp/lineitemedit/assets/85277674/f7cf826c-5bd8-4b06-ad34-2b7023ae4dea)

## After
Users can now input decimal quantities when editing the line items.

![qqqqq](https://github.com/compucorp/lineitemedit/assets/85277674/ae6425a8-4f03-477e-ac82-8b17c42e2941)

2023-06-12 08:58 UTC, olayiwola-compucorp commented
Sure, that was what we agreed on @jamienovick , or do you mean this should go first to the module maintainer?

2023-06-12 09:01 UTC, jamienovick commented
Either is fine (although I guess they may come up with a different solution) many thanks! @olayiwola-compucorp

2023-06-13 12:44 UTC, olayiwola-compucorp commented
PR created to extension maintainer https://lab.civicrm.org/extensions/lineitemedit/-/merge_requests/77

2023-07-04 16:03 UTC, jamienovick commented
@omarabuhussein 

Amounts/weights aren't always integers. You could have 4.5KG of something for example, but in our specific case when we bill a % of something, we need to bill only that % (which will be a decimal). Is that enough detail?

2023-07-04 18:07 UTC, olayiwola-compucorp commented
Thanks @jamienovick;

Furthermore @omarabuhussein, since the line item quantity field on the create screen accepts decimal input, I believe it is reasonable to expect that the quantity field on the edit screen should also support decimal values.

2023-07-05 09:26 UTC, omarabuhussein requested changes
Can you update the following places as well:

- https://github.com/compucorp/lineitemedit/blob/BTHAB-188-contrib-qty/CRM/Lineitemedit/Util.php#L589
- https://github.com/compucorp/lineitemedit/blob/BTHAB-188-contrib-qty/lineitemedit.php#L179

also I would wait anyway for the maintainers to respond on the original PR in case there is something we are not aware of.

2023-07-06 07:42 UTC, olayiwola-compucorp commented
Hi @omarabuhussein, I believe these two recommended changes are outside the scope of this PR 

The objective of this PR is to guarantee that if a user creates a line item with a decimal quantity the decimal points are not lost when editing the line item; basically, we are saying if I create a line item with quantity = 1.34, editing the line item should not change the quantity to 1. This justifies why the change is only limited to `CRM/Lineitemedit/Form/Edit.php`.


Aside that;
- https://github.com/compucorp/lineitemedit/blob/BTHAB-188-contrib-qty/CRM/Lineitemedit/Util.php#L589 I believe this is okay to be int, as stated in the PHP doc that the `function is used to add membership or participant record on adding related line-item` 
- https://github.com/compucorp/lineitemedit/blob/BTHAB-188-contrib-qty/lineitemedit.php#L179 - Likewise here, there's support for decimal quantity for line items that are from a user text input already.

2023-07-06 09:10 UTC, omarabuhussein commented
@olayiwola-compucorp well, updating these make things more consistent across the extension code, and I would say that such changes are not that far from the scope of this ticket, at the end of the day the ticket is more about the ability of this extension to handle "decimal" quantities,  and both of these changes are simple to do anyway. 

In general I find it is limiting for any developer to only think about the scope of the ticket when working on any ticket, it is important to keep an eye on how your changes fit within the whole extension/product.

2023-07-06 09:51 UTC, omarabuhussein approved these changes

2023-08-25 08:07 UTC, merged